# Generated by Django 3.1.4 on 2021-01-03 18:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Jogador')),
                ('team', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Time')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inhouse.server')),
            ],
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BLUE', 'BLUE'), ('RED', 'RED')], db_index=True, max_length=4, verbose_name='Lado')),
                ('role', models.CharField(choices=[('TOP', 'TOP'), ('JGL', 'JGL'), ('MID', 'MID'), ('BOT', 'BOT'), ('SUP', 'SUP')], db_index=True, max_length=4, verbose_name='Role')),
                ('champion_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Campeão')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Jogador')),
                ('trueskill_mu', models.DecimalField(db_index=True, decimal_places=4, max_digits=6, verbose_name='trueskill_mu')),
                ('trueskill_sigma', models.DecimalField(db_index=True, decimal_places=4, max_digits=6, verbose_name='trueskill_sigma')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inhouse.player')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Início')),
                ('blue_expected_winrate', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Blue-side Winrate Experado')),
                ('winner', models.CharField(blank=True, choices=[('BLUE', 'BLUE'), ('RED', 'RED')], default='', max_length=4, null=True, verbose_name='Vencedor')),
                ('participants', models.ManyToManyField(related_name='game', to='inhouse.GameParticipant')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inhouse.server')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelInformation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel_type', models.CharField(choices=[('RANKING', 'RANKING'), ('QUEUE', 'QUEUE')], max_length=200, verbose_name='Tipo de Canal')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inhouse.server')),
            ],
        ),
        migrations.CreateModel(
            name='QueuePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TOP', 'TOP'), ('JGL', 'JGL'), ('MID', 'MID'), ('BOT', 'BOT'), ('SUP', 'SUP')], db_index=True, max_length=4, verbose_name='Role')),
                ('queue_time', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Data de entrada na fila')),
                ('ready_check_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Confirmação')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inhouse.channelinformation')),
                ('duo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inhouse.queueplayer')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inhouse.player')),
            ],
            options={
                'unique_together': {('channel', 'player', 'role')},
            },
        ),
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TOP', 'TOP'), ('JGL', 'JGL'), ('MID', 'MID'), ('BOT', 'BOT'), ('SUP', 'SUP')], db_index=True, max_length=4, verbose_name='Role')),
                ('trueskill_mu', models.DecimalField(db_index=True, decimal_places=4, default=25, max_digits=6, verbose_name='trueskill_mu')),
                ('trueskill_sigma', models.DecimalField(db_index=True, decimal_places=4, default=8.333333333333334, max_digits=6, verbose_name='trueskill_sigma')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inhouse.player')),
            ],
            options={
                'unique_together': {('player', 'role')},
            },
        ),
    ]
