# Generated by Django 3.1.4 on 2021-01-05 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inhouse', '0002_auto_20210103_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueplayer',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='inhouse.channelinformation'),
        ),
    ]
