# Generated by Django 3.1.4 on 2021-01-05 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inhouse', '0003_auto_20210105_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='participants',
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='inhouse.game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='blue_expected_winrate',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True, verbose_name='Blue-side Winrate Experado'),
        ),
    ]
