# Generated by Django 3.1.4 on 2021-01-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inhouse', '0004_auto_20210105_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='chanel_category',
            new_name='channel_category',
        ),
    ]
