# Generated by Django 3.1.4 on 2021-01-06 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inhouse', '0005_auto_20210105_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='channel_category',
            new_name='chanel_category',
        ),
    ]
