# Generated by Django 3.1.4 on 2021-01-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inhouse', '0006_auto_20210106_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='chanel_category',
            new_name='channel_category',
        ),
    ]
